package com.model;

import java.util.Date;

/**
 * Announcement generated by MyEclipse Persistence Tools
 */

public class Announcement implements java.io.Serializable
{

	// Fields

	private Integer announcementId;

	private String announcementTitle;

	private String announcementContent;

	private String announcementData;


	
	private String announcementDel;



	// Constructors

	/** default constructor */
	public Announcement()
	{
	}

	/** full constructor */
	public Announcement(String announcementTitle, String announcementContent,
			Date announcementData )
	{
		this.announcementTitle = announcementTitle;
		this.announcementContent = announcementContent;

	}

	// Property accessors

	public Integer getAnnouncementId()
	{
		return this.announcementId;
	}

	public void setAnnouncementId(Integer announcementId)
	{
		this.announcementId = announcementId;
	}

	public String getAnnouncementTitle()
	{
		return this.announcementTitle;
	}

	public void setAnnouncementTitle(String announcementTitle)
	{
		this.announcementTitle = announcementTitle;
	}

	public String getAnnouncementContent()
	{
		return this.announcementContent;
	}

	public void setAnnouncementContent(String announcementContent)
	{
		this.announcementContent = announcementContent;
	}


	public String getAnnouncementData()
	{
		return announcementData;
	}

	public void setAnnouncementData(String announcementData)
	{
		this.announcementData = announcementData;
	}





	public String getAnnouncementDel()
	{
		return announcementDel;
	}

	public void setAnnouncementDel(String announcementDel)
	{
		this.announcementDel = announcementDel;
	}

}