package com.model;

/**
 * Comment generated by MyEclipse Persistence Tools
 */

public class Comment implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer novelId;

	private String content;

	private String createTime;

	// Constructors

	/** default constructor */
	public Comment()
	{
	}

	/** full constructor */
	public Comment(Integer novelId, String content, String createTime)
	{
		this.novelId = novelId;
		this.content = content;
		this.createTime = createTime;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getnovelId()
	{
		return this.novelId;
	}

	public void setnovelId(Integer novelId)
	{
		this.novelId = novelId;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getCreateTime()
	{
		return this.createTime;
	}

	public void setCreateTime(String createTime)
	{
		this.createTime = createTime;
	}

}