package com.model;

/**
 * Novel generated by MyEclipse Persistence Tools
 */

public class Novel implements java.io.Serializable
{

	// Fields

	private Integer novelId;

	private String novelName;

	private String novelMiaoshu;

	private String novelPic;

	private String novelYanse;
	private String novelAuthor;

	private Integer novelLikeNum;

	private Integer novelRecommendWeight;

	private String novelIsrecommend;



	private Integer novelCatelogId;
	
	private String novelKucun;
	
	private String novelDel;
	
	private String novelCatelogName;//数据库表没有，自己添加的

	// Constructors

	/** default constructor */
	public Novel()
	{
	}

	/** full constructor */
	public Novel(String novelName, String novelMiaoshu, String novelPic,
				 String novelYanse, Integer novelLikeNum, Integer novelRecommendWeight,

				 Integer novelCatelogId)
	{
		this.novelName = novelName;
		this.novelMiaoshu = novelMiaoshu;
		this.novelPic = novelPic;
		this.novelYanse = novelYanse;
		this.novelLikeNum = novelLikeNum;
		this.novelRecommendWeight = novelRecommendWeight;
		this.novelIsrecommend = novelIsrecommend;

		this.novelCatelogId = novelCatelogId;
	}

	// Property accessors

	public Integer getNovelId()
	{
		return this.novelId;
	}

	public String getNovelDel()
	{
		return novelDel;
	}

	public String getNovelKucun()
	{
		return novelKucun;
	}

	public void setNovelKucun(String novelKucun)
	{
		this.novelKucun = novelKucun;
	}

	public void setNovelDel(String novelDel)
	{
		this.novelDel = novelDel;
	}

	public void setNovelId(Integer novelId)
	{
		this.novelId = novelId;
	}

	public String getNovelName()
	{
		return this.novelName;
	}

	public void setNovelName(String novelName)
	{
		this.novelName = novelName;
	}

	public String getNovelMiaoshu()
	{
		return this.novelMiaoshu;
	}

	public void setNovelMiaoshu(String novelMiaoshu)
	{
		this.novelMiaoshu = novelMiaoshu;
	}

	public String getNovelPic()
	{
		return this.novelPic;
	}

	public void setNovelPic(String novelPic)
	{
		this.novelPic = novelPic;
	}

	public String getNovelYanse()
	{
		return this.novelYanse;
	}

	public void setNovelYanse(String novelYanse)
	{
		this.novelYanse = novelYanse;
	}

	public Integer getNovelLikeNum()
	{
		return this.novelLikeNum;
	}

	public void setNovelLikeNum(Integer novelLikeNum)
	{
		this.novelLikeNum = novelLikeNum;
	}

	public Integer getNovelRecommendWeight()
	{
		return this.novelRecommendWeight;
	}

	public void setNovelRecommendWeight(Integer novelRecommendWeight)
	{
		this.novelRecommendWeight = novelRecommendWeight;
	}

	public String getNovelIsrecommend()
	{
		return this.novelIsrecommend;
	}

	public void setNovelIsrecommend(String novelIsrecommend)
	{
		this.novelIsrecommend = novelIsrecommend;
	}

	public String getNovelAuthor() {
		return novelAuthor;
	}

	public void setNovelAuthor(String novelAuthor) {
		this.novelAuthor = novelAuthor;
	}





	public Integer getNovelCatelogId()
	{
		return this.novelCatelogId;
	}

	public void setNovelCatelogId(Integer novelCatelogId)
	{
		this.novelCatelogId = novelCatelogId;
	}

	public String getNovelCatelogName()
	{
		return novelCatelogName;
	}

	public void setNovelCatelogName(String novelCatelogName)
	{
		this.novelCatelogName = novelCatelogName;
	}

}