package com.model;

/**
 * Novel generated by MyEclipse Persistence Tools
 */

public class Novel implements java.io.Serializable
{

	// Fields

	private Integer novelId;

	private String novelName;

	private String novelMiaoshu;

	private String novelPic;

	private String novelYanse;
	private String novelAuthor;

	private Integer novelShichangjia;

	private Integer novelTejia;

	private String novelIsnottejia;

	private String novelIsnottuijian;

	private Integer novelCatelogId;
	
	private String novelKucun;
	
	private String novelDel;
	
	private String novelCatelogName;//数据库表没有，自己添加的

	// Constructors

	/** default constructor */
	public Novel()
	{
	}

	/** full constructor */
	public Novel(String novelName, String novelMiaoshu, String novelPic,
				 String novelYanse, Integer novelShichangjia, Integer novelTejia,
				 String novelIsnottejia, String novelIsnottuijian,
				 Integer novelCatelogId)
	{
		this.novelName = novelName;
		this.novelMiaoshu = novelMiaoshu;
		this.novelPic = novelPic;
		this.novelYanse = novelYanse;
		this.novelShichangjia = novelShichangjia;
		this.novelTejia = novelTejia;
		this.novelIsnottejia = novelIsnottejia;
		this.novelIsnottuijian = novelIsnottuijian;
		this.novelCatelogId = novelCatelogId;
	}

	// Property accessors

	public Integer getNovelId()
	{
		return this.novelId;
	}

	public String getNovelDel()
	{
		return novelDel;
	}

	public String getNovelKucun()
	{
		return novelKucun;
	}

	public void setNovelKucun(String novelKucun)
	{
		this.novelKucun = novelKucun;
	}

	public void setNovelDel(String novelDel)
	{
		this.novelDel = novelDel;
	}

	public void setNovelId(Integer novelId)
	{
		this.novelId = novelId;
	}

	public String getNovelName()
	{
		return this.novelName;
	}

	public void setNovelName(String novelName)
	{
		this.novelName = novelName;
	}

	public String getNovelMiaoshu()
	{
		return this.novelMiaoshu;
	}

	public void setNovelMiaoshu(String novelMiaoshu)
	{
		this.novelMiaoshu = novelMiaoshu;
	}

	public String getNovelPic()
	{
		return this.novelPic;
	}

	public void setNovelPic(String novelPic)
	{
		this.novelPic = novelPic;
	}

	public String getNovelYanse()
	{
		return this.novelYanse;
	}

	public void setNovelYanse(String novelYanse)
	{
		this.novelYanse = novelYanse;
	}

	public Integer getNovelShichangjia()
	{
		return this.novelShichangjia;
	}

	public void setNovelShichangjia(Integer novelShichangjia)
	{
		this.novelShichangjia = novelShichangjia;
	}

	public Integer getNovelTejia()
	{
		return this.novelTejia;
	}

	public void setNovelTejia(Integer novelTejia)
	{
		this.novelTejia = novelTejia;
	}

	public String getNovelIsnottejia()
	{
		return this.novelIsnottejia;
	}

	public void setNovelIsnottejia(String novelIsnottejia)
	{
		this.novelIsnottejia = novelIsnottejia;
	}

	public String getNovelAuthor() {
		return novelAuthor;
	}

	public void setNovelAuthor(String novelAuthor) {
		this.novelAuthor = novelAuthor;
	}

	public String getNovelIsnottuijian()
	{
		return this.novelIsnottuijian;
	}

	public void setNovelIsnottuijian(String novelIsnottuijian)
	{
		this.novelIsnottuijian = novelIsnottuijian;
	}

	public Integer getNovelCatelogId()
	{
		return this.novelCatelogId;
	}

	public void setNovelCatelogId(Integer novelCatelogId)
	{
		this.novelCatelogId = novelCatelogId;
	}

	public String getNovelCatelogName()
	{
		return novelCatelogName;
	}

	public void setNovelCatelogName(String novelCatelogName)
	{
		this.novelCatelogName = novelCatelogName;
	}

}