package com.model;

import java.util.Date;

/**
 * TGonggao generated by MyEclipse Persistence Tools
 */

public class TGonggao implements java.io.Serializable
{

	// Fields

	private Integer gonggaoId;

	private String gonggaoTitle;

	private String gonggaoContent;

	private String gonggaoData;


	
	private String gonggaoDel;



	// Constructors

	/** default constructor */
	public TGonggao()
	{
	}

	/** full constructor */
	public TGonggao(String gonggaoTitle, String gonggaoContent,
			Date gonggaoData )
	{
		this.gonggaoTitle = gonggaoTitle;
		this.gonggaoContent = gonggaoContent;

	}

	// Property accessors

	public Integer getGonggaoId()
	{
		return this.gonggaoId;
	}

	public void setGonggaoId(Integer gonggaoId)
	{
		this.gonggaoId = gonggaoId;
	}

	public String getGonggaoTitle()
	{
		return this.gonggaoTitle;
	}

	public void setGonggaoTitle(String gonggaoTitle)
	{
		this.gonggaoTitle = gonggaoTitle;
	}

	public String getGonggaoContent()
	{
		return this.gonggaoContent;
	}

	public void setGonggaoContent(String gonggaoContent)
	{
		this.gonggaoContent = gonggaoContent;
	}


	public String getGonggaoData()
	{
		return gonggaoData;
	}

	public void setGonggaoData(String gonggaoData)
	{
		this.gonggaoData = gonggaoData;
	}





	public String getGonggaoDel()
	{
		return gonggaoDel;
	}

	public void setGonggaoDel(String gonggaoDel)
	{
		this.gonggaoDel = gonggaoDel;
	}

}