package com.model;

/**
 * TOrderItem generated by MyEclipse Persistence Tools
 */

public class TOrderItem implements java.io.Serializable
{

	// Fields

	private Integer orderItemId;

	private Integer orderId;

	private Integer novelId;

	private Integer novelQuantity;
	
	private Novel novel;//表里没有。自己加的

	// Constructors

	/** default constructor */
	public TOrderItem()
	{
	}

	/** full constructor */
	public TOrderItem(Integer orderId, Integer novelId, Integer novelQuantity)
	{
		this.orderId = orderId;
		this.novelId = novelId;
		this.novelQuantity = novelQuantity;
	}

	// Property accessors

	public Integer getOrderItemId()
	{
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId)
	{
		this.orderItemId = orderItemId;
	}

	public Integer getOrderId()
	{
		return this.orderId;
	}

	public void setOrderId(Integer orderId)
	{
		this.orderId = orderId;
	}

	public Integer getNovelId()
	{
		return this.novelId;
	}

	public Novel getNovel()
	{
		return novel;
	}

	public void setNovel(Novel novel)
	{
		this.novel = novel;
	}

	public void setNovelId(Integer novelId)
	{
		this.novelId = novelId;
	}

	public Integer getNovelQuantity()
	{
		return this.novelQuantity;
	}

	public void setNovelQuantity(Integer novelQuantity)
	{
		this.novelQuantity = novelQuantity;
	}

}