package com.model;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class Tzhangjie implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String content;

	private String pushtime;
	
	private String zhangjiename;
	
	private Integer novelId;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPushtime() {
		return pushtime;
	}

	public void setPushtime(String pushtime) {
		this.pushtime = pushtime;
	}

	public String getZhangjiename() {
		return zhangjiename;
	}

	public void setZhangjiename(String zhangjiename) {
		this.zhangjiename = zhangjiename;
	}

	public Integer getNovelId() {
		return novelId;
	}

	public void setNovelId(Integer novelId) {
		this.novelId = novelId;
	}

	// Constructors

	
}